#!/usr/bin/env Rscript

## Script to extract the set of tissue (or other data type) specific outliers from multi-tissue outliers
## Author: Emily K. Tsang, 2017
## Modified: Nicole Ferraro, 2019

library(data.table)
library(dplyr)
library(ggplot2)
library(argparse)

## Functions
## Function that returns the tissues or data type with |Z-score| > threshold - assumes absolute value is desired
## Input: vector with Ind and Gene that defines the outlier, in columns 1 and 2, respectively
##        threshold for calling a tissue or data type extreme
##        name of the column with the tissue or data type
## Output: list of tissues or data type with extreme expression, or max value if return_val is TRUE
get.extreme <- function(outlier_info, thresh = 2, col_name = 'Tissue', return_val=FALSE, restrict=FALSE) {
    ind = outlier_info[1]
    gene = outlier_info[2]
    data_df = as.data.frame(data[gene,c(col_name,ind),with=F])
    if (return_val) {
        rind = which(abs(data_df[,2]) == max(abs(data_df[,2]),na.rm=T))
        return(data_df[rind,2])
    }
    indices = abs(data_df[, ind]) > thresh & !is.na(data_df[, ind])
    groups = sort(data_df[indices, col_name]) 
    return(groups)
}

## Function that takes a data frame of outliers and a threshold for calling specific outliers
## that returns the same outliers data frame with a column added with the name
## of the specificity group (or NA if the outliers is not specific)
filter.specific <- function(outliers, thresh) {
    outliers$data_value = apply(outliers, 1, filter.specific.helper, thresh, return_val=T)
    outliers$Specific.Group = apply(outliers, 1, filter.specific.helper, thresh, return_val=F)
    return(outliers)
}

## Helper function that takes vector where the first two elements are gene and individual
## Returns the name of the specific group, if applicable, or NA
## A specific group is returned if only a single measurement has Z-score above the given threshold.
filter.specific.helper <-  function(outlier_info, thresh, return_val) {
    col_name = 'Tissue'
    groups = get.extreme(outlier_info, thresh, col_name, return_val, restrict=FALSE)
    if (return_val) { return(groups) }
    if (length(unique(groups)) != 1) {
        return(NA)
    } else {
        return(groups)
    }
}

## Input files
parser = ArgumentParser()
parser$add_argument('--OUTLIER.FILE', help = 'Complete path to outlier file generated by call_outliers')
parser$add_argument('--OUT.FILE', help = 'Path of output file')
parser$add_argument('--DATA.FILE', help = 'Gzipped file with original data')
parser$add_argument('--THRESH', default = 2, help = 'Specificity threshold (assumes Z-scores for default)')
parser$add_argument('--FDR', default = 0.01, help = 'Outlier threshold')
args = parser$parse_args()


cor_data = fread(args$OUTLIER.FILE,data.table=F) 
fdr_thresh = args$FDR
outliers = filter(cor_data,FDR < fdr_thresh) %>% mutate(Y = 'outlier')
controls = filter(cor_data,FDR > fdr_thresh | is.na(FDR), Gene %in% outliers$Gene) %>% mutate(Y = 'control', Specific.Group=NA)

data = fread(paste('zcat', args$DATA.FILE))
setkey(data, Gene)

## update outlier data frames to contain information on specificity
outliers.controls.specific = filter.specific(outliers, args$THRESH)

outliers.controls.specific = rbind(outliers.controls.specific, 
                                   controls %>% mutate(data_value = NA))

write.table(outliers.controls.specific, file = args$OUT.FILE, sep='\t', quote=F, row.names=F)

